apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: classifieds-sql-secret-csi
  namespace: classifieds
spec:
  provider: azure
  secretObjects:
    - secretName: azsql-db-connectionstring-classifieds
      type: Opaque
      data:
      - objectName: AzSql-Db-ConnectionString-Classifieds
        key: azsql-db-connectionstring-classifieds
    - secretName: azsql-db-connectionstring-timetracker
      type: Opaque
      data:
      - objectName: AzSql-Db-ConnectionString-TimeTracker
        key: azsql-db-connectionstring-timetracker
  parameters:
    keyvaultName: kvakslzaccel234
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 92598350-519b-4281-a3f3-c19afb1ef214 # the client ID of the MSI
    cloudName: ""
    objects:   |
      array:
        - |
          objectName: AzSql-Db-ConnectionString-Classifieds
          objectType: secret
          objectVersion: ""
        - |
          objectName: AzSql-Db-ConnectionString-TimeTracker
          objectType: secret
          objectVersion: ""
    tenantId: c4c9004b-43cc-4303-bfbf-0a5f7e1d0139